### ISSUE TITLE
exception in 1.0.0 beta 3.4

### ISSUE THREAD

**Issue by fvergani-sumo** [ivanovych666/intellij-json-sorter-plugin#12]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.ivanovych666.intellij.plugin.jsonsorter.JSONSorterGroup' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.ivanovych666.intellij.plugin.jsonsorter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
<img width="1197" alt="image" src="https://github.com/ivanovych666/intellij-json-sorter-plugin/assets/98739903/296534cf-58d5-4e3c-a954-c943b7e4350c">

**Comment by ivanovych666** [comment]
The issue with `ActionUpdateThread.OLD_EDT is deprecated` already fixed. The new version `2.0.0` is available in the JetBrains Marketplace.
