### ISSUE TITLE
Crash in clion

### ISSUE THREAD

**Issue by wcarmon** [ivanovych666/intellij-json-sorter-plugin#13]
version: `1.0.0-beta.3.4`

# Plugin Exception
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.ivanovych666.intellij.plugin.jsonsorter.JSONSorterGroup' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.ivanovych666.intellij.plugin.jsonsorter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

# IDE info
```
CLion 2024.2.0.1
Build #CL-242.20224.413, built on August 18, 2024
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.8.0-41-generic
.NET Core v8.0.4 x64 (Server GC)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 6000M
Cores: 32
Registry:
  actionSystem.update.actions.warn.dataRules.on.edt=false
  debugger.attach.dialog.enabled=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  ide.slow.operations.assertion=false
  cache.folding.model.on.disk=false
  org.toml.json.schema=false
Non-Bundled Plugins:
  com.jetbrains.rust (242.20224.421)
  com.ivanovych666.intellij.plugin.jsonsorter (1.0.0-beta.3.4)
Current Desktop: XFCE
```

**Comment by ivanovych666** [comment]
The issue with `ActionUpdateThread.OLD_EDT is deprecated` already fixed. The new version `2.0.0` is available in the JetBrains Marketplace.
